# Generated by Django 2.1.2 on 2019-10-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp_adrees', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('user', models.CharField(max_length=50)),
                ('error_code', models.CharField(max_length=50)),
                ('memory', models.IntegerField()),
                ('loction', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
            ],
        ),
    ]
