# Generated by Django 2.1.2 on 2019-10-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapp', '0002_log_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log_fields',
        ),
    ]
