# Generated by Django 2.1.2 on 2019-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapp', '0003_delete_log_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp_adrees', models.CharField(max_length=20)),
                ('date_time', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('res_code', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('url_loction', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
            ],
        ),
    ]
