# Generated by Django 2.1.2 on 2019-10-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapp', '0004_log_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_fields',
            name='user',
        ),
    ]
